import Image from "next/image";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import Formpage from "./Components/Formpage";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Flowbite-React",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Navbar />
      <Formpage />
      <Footer />
    </>
  );
}
